### PR TITLE
Include generated_date in the response

### LINKED ISSUE #1506: Add new generated_time field to json view
I'd like to be able to see this when I look at a dump via the Events UI.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Fixes #1506

### CODE REVIEW

**Review by tpendragon — CHANGES_REQUESTED** [review]
Suggestion: Can we get a test?

**Comment by hectorcorrea** [comment]
@tpendragon test has been added

**Comment by tpendragon** [comment]
@hectorcorrea CI's failing, maybe time-zone business?

**Comment by hectorcorrea** [comment]
@tpendragon yup, thanks for the heads up. Fixed. 🤞🏼

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
