### PR TITLE
Update locations gem to v1.5 to include library in the delivery locations

### LINKED ISSUE #1376: Alma Delivery location supplied in a holding location should include the library code
Alma required a library code like 'firestone' for delivery.  The data returned by  https://bibdata-alma-staging.princeton.edu/locations/delivery_locations.json includes a location code.  But the delivery location returned as part of a holding location does not https://bibdata-alma-staging.princeton.edu/locations/holding_locations/firestone$stacks.json

The location code is needed by alma to get the correct pickup information.  Could it please be returned in the first URL

### PR DESCRIPTION
**Pull request by christinach**
closes #1376

### CODE REVIEW

**Comment by christinach** [comment]
This is pointing to https://github.com/pulibrary/locations/pull/90/files until it gets merged and we create a new tag1.5.0.

**Comment by christinach** [comment]
Now it points to location v1.5.0

**Review by hackartisan — COMMENTED** [review]
Did you mean to update all these other things too?

You can do `bundle update locations --conservative` to get just the minimal updates

**Comment by christinach** [comment]
> Did you mean to update all these other things too?
> 
> You can do `bundle update locations --conservative` to get just the minimal updates

I meant to update them but I can do the conservative as well. I checked OL has similar updates from a recent requests update.

**Review by hackartisan — APPROVED** [review]

**Comment by hackartisan** [comment]
I usually run bundle updates that way, just to minimize unexpected bugs.

**Comment by christinach** [comment]
example of included library in delivery locations https://bibdata-alma-staging.princeton.edu/locations/holding_locations/firestone$gss.json

**Comment by christinach** [comment]
ok updated  `--conservative` @hackartisan

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
