### PR TITLE
Replace -> with → in docs/db_migration.md

### LINKED ISSUE #2203: -> arrows are misleading, as they are read as "greater than" by screen readers in docs/db_migration.md
### Steps to recreate
Visit docs/db_migration.md

### URL
[Alma document](https://github.com/pulibrary/bibdata/blob/main/docs/db_migration.md)

### Issues
-> arrows are misleading, as they are read as "greater than" by screen readers.

### Severity
Low

### WCAG Conformance level (A, AA, AAA)
A

### User impact
User may be confused by screen reader reading "greater than" rather than "arrow"

### Recommended fix
Replace -> with →

### Acceptance criteria
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Notes

### PR DESCRIPTION
**Pull request by lizgarciao**
closes #2203

### CODE REVIEW

**Review by christinach — CHANGES_REQUESTED** [review]
the rebase removed correct fixes. we need to update the pr again.

**Comment by lizgarciao** [comment]
> 

Should I just make the link change in this PR so we can merge it?

**Comment by christinach** [comment]
@lizgarciao if you pull the recent changes in main and then you rebase your branch you will be able to resolve the conflict and update the PR with a force push.
Thanks!

**Comment by lizgarciao** [comment]
It seems that I made two PRs to accomplish the same changes. 
I realized this with Jane!

**Pull request closed without merging**
