### PR TITLE
Reimplement RecapTransferJob as RecapTransferService

### PR DESCRIPTION
**Pull request by eliotjordan**
Hopefully this refactor will solve the issues with scsb record uploads, or, at the least, provide some insight as to the job behavior on the staging sidekiq workers.

Work towards #1336

### CODE REVIEW

**Comment by tpendragon** [comment]
What happens now if the transfer fails? Will it re-process the SCSB file?

**Comment by eliotjordan** [comment]
@tpendragon The error should cause the dumpfile / boundwiths-file processing jobs to restart and re-proccess the file.

**Comment by tpendragon** [comment]
@eliotjordan And that's safe?

**Comment by eliotjordan** [comment]
@tpendragon The original dump file is never altered. The processed file is saved as a tempfile and sent to S3. That was happening before this PR. If the transfer fails, the only penalty should be the extra time to run the job again. It was the way to get these to be idempotent.

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
