### PR TITLE
Upgrade ruby 2.7.5

### LINKED ISSUE #1755: Upgrade ruby to version 2.7.5
following https://github.com/pulibrary/bibdata/issues/589:
- [x]  Add Ruby 2.7.5 to CircleCI
- [x]  Fix any failing tests or dependency issues caused by upgrade to 2.7.5
- [ ]  Deploy code that hopefully works with both 2.6 and 2.7.5
- [ ]  Provision boxes to use Ruby 2.7.5 (yes for staging https://github.com/pulibrary/princeton_ansible/tree/upgrade-ruby-bibdata-staging)
- [ ]  Remove Ruby 2.6 from CircleCI

### PR DESCRIPTION
**Pull request by christinach**
closes #1755 

- [x] Deploy on staging (after provisioning bibdata staging https://github.com/pulibrary/princeton_ansible/tree/upgrade-ruby-2.7-bibdata)
- [x] Index some records
- [x] update webhook
- [x] @mzelesky deactivated again the staging webhook in alma prod box. We triggered an incremental publishing job. We expect files to come in bibdata_staging on Monday 01/24/2022. If not look into why files are not coming. https://github.com/pulibrary/bibdata/issues/1758

### CODE REVIEW

**Comment by christinach** [comment]
The records are being indexed but I see this warning `/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.unescape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.escape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.unescape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.escape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.unescape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.escape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.unescape is obsolete
/opt/marc_liberation/releases/20220120155119/marc_to_solr/lib/normal_uri_factory.rb:21: warning: URI.escape is obsolete` which is annoying and should be fixed.

**Comment by christinach** [comment]
Changes that were made in the alma sandbox came through in bibdata-staging and were indexed. Latest incremental that was triggered in Alma, created event/dump with id 684 in bibdata-staging. 
The event that was logged in AWS from this Alma job is: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Falma-webhook-monitor-staging-WebhookReceiver-za2o0tUQ0XNM/log-events/2022$252F01$252F25$252F$255B$2524LATEST$255D62f4a9779bcf41a7b3f81b1f0f82869e 
Checking the console it's the last one (as of now) that IndexManager has as a last_dump_completed_id
<IndexManager id: 1, solr_collection: "http://lib-solr8-staging.princeton.edu:8983/solr/catalog-alma-staging", dump_in_progress_id: nil, last_dump_completed_id: 684, created_at: "2021-08-10 20:51:17", updated_at: "2022-01-25 21:47:33", in_progress: false>

IndexManager.first.last_dump_completed.event
=> #<Event id: 684, start: "2022-01-25 21:09:40", finish: "2022-01-25 21:47:24", error: nil, success: true, created_at: "2022-01-25 21:47:31", updated_at: "2022-01-25 21:47:31", message_body: "{\"id\":\"**14950549970006421**\",\"action\":\"JOB_END\",\"inst..."> (id from message body in bold is the id that can be identified in the AWS event log - url pasted above)

IndexManager.first.last_dump_completed
=> #<Dump id: 684, event_id: 684, dump_type_id: 2, delete_ids: nil, created_at: "2022-01-25 21:47:31", updated_at: "2022-01-25 21:47:31", update_ids: nil, create_ids: nil, index_status: nil, generated_date: "2022-01-25 21:09:40">

Also AWS is updated to 2.7:
https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/alma-webhook-monitor-staging-WebhookReceiver-za2o0tUQ0XNM?tab=code

We should try to deploy early in the morning before 9:00am. The current schedule from Alma triggering Incremental Publishing jobs is: **04:00, 10:00, 16:00, 22:00**

**Review by carolyncole — COMMENTED** [review]
@christinach my only comment is you can use below to avoid all the spacing changes.
```
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
```

**Comment by christinach** [comment]
I adde the rubocop rule @carolyncole thank you

**Review by carolyncole — APPROVED** [review]

**Pull request merged**
