### PR TITLE
Delivery locations for engineering is gfa_pickup PT - Engineering Library

### LINKED ISSUE #1578: Update the location tables in bibdata following the external name changes in Alma
Changes are from issues: https://github.com/pulibrary/bibdata/issues/1556 and 
https://github.com/pulibrary/bibdata/issues/1568

### LINKED ISSUE #1580: Update delivery locations for all the engineering locations
All engineering locations need to point to engineering delivery location.
Delivery location with gfa_pickup: PT (https://bibdata.princeton.edu/locations/delivery_locations/5)

Update the holding_locations.json file: "delivery_locations" should have PT for all the engineering locations.

### PR DESCRIPTION
**Pull request by christinach**
closes #1580 
closes #1578

### CODE REVIEW

**Comment by christinach** [comment]
@kevinreiss I noticed that in bibdata not all the engineering holdings_locations have delivery location the Engineering Library. Some have delivery location Lewis and some nothing. 
engineer$pt has many delivery locations. 

Can you add in a comment which of the Engineering locations need to have delivery location PT and if some need to have more that one delivery locations which are they? So that I can update the file accordingly.

**Comment by christinach** [comment]
In this Pr I update all the engineer$... locations to have delivery location only PT as you said.

**Comment by christinach** [comment]
per @kevinreiss update engineer$pt to have the same delivery locations as  https://bibdata.princeton.edu/locations/holding_locations/recap$pa

**Comment by christinach** [comment]
@kevinreiss I will populate the locations in bibdata-staging and let you know to check

**Comment by christinach** [comment]
@kevinreiss  can you check the ui https://bibdata-staging.princeton.edu/holding_locations ? All the engineer locations should have delivery library: pt (The Engineer Library). Only engineer$pt has delivery locations : all the delivery libraries.
Can you confirm that is ok if I remove from the delivery locations the second ‘PT’ Engineering Library Off-Site Storage’ ? We had it in voyager but the gfa_pickup should be unique.

@Trey if I remove from the delivery_locations.json delivery location with id:40 will it break figgy? https://github.com/pulibrary/bibdata/blob/f30d87682d1c87231695194998155ce14d522259/config/locations/delivery_locations.json#L417 (edited)

**Comment by trey** [comment]
👋🏻 Hi, I think you've got the wrong Trey. :)

**Comment by tpendragon** [comment]
@trey Nice to meet you other Trey. :)

We can delete that entry, should be fine.

**Comment by christinach** [comment]
> 👋🏻 Hi, I think you've got the wrong Trey. :)

Hi Trey! and sorry for tagging you!

**Review by kevinreiss — APPROVED** [review]

**Pull request merged**
