### PR TITLE
Update rsolr to get recent fixes

### LINKED ISSUE #1391: uninitialized constant Faraday::Error::ConnectionFailed
The error "uninitialized constant Faraday::Error::ConnectionFailed" is obscuring other errors and can be resolved by updating rsolr

https://github.com/rsolr/rsolr/compare/v2.1.0...master

Most recent honeybadger error was: https://app.honeybadger.io/projects/54497/faults/79785330

### PR DESCRIPTION
**Pull request by hackartisan**
resolves #1391 and should stop us from getting the Uninitialized
Constant error on Faraday

### CODE REVIEW

**Comment by christinach** [comment]
@hackartisan did you check out from the `alma` branch?
Do we want to apply this change in the `main` branch?
These errors come from the `main` deployment, aren't they?

**Comment by christinach** [comment]
Seeing the honeybadger notes it's on the catalog-rebuild which is `main` deployment.

**Comment by hackartisan** [comment]
@christinach the most recent honeybadger error was on bibdata-alma-worker1: https://app.honeybadger.io/projects/54497/faults/79785330

I tried to look at the older honeybadger notices but they didn't have any more data. if you have been seeing this in prod, though, I will go ahead and do it on main.

**Comment by christinach** [comment]
@hackartisan I checked this error the note I had added https://app.honeybadger.io/projects/54497/faults/74535246. It was linked on issue https://github.com/pulibrary/bibdata/issues/1391

**Comment by hackartisan** [comment]
closed in favor of https://github.com/pulibrary/bibdata/pull/1393

**Pull request closed without merging**
