### PR TITLE
check in holding_library.rb

### LINKED ISSUE #1168: Populate the bibdata tables with the desired recap location names that are included in the issue.
This is the content that we want the holding_library.rb to have

{ "recap$gp" => "Firestone Library",
  "recap$pb" => "Firestone Library",
  "recap$pf" => "Firestone Library",
  "recap$pg" => "Rare Books and Special Collections",
  "recap$ph" => "Mudd Manuscript Library",
  "recap$pj" => "Marquand Library",
  "recap$pk" => "Mendel Music Library",
  "recap$pl" => "East Asian Library",
  "recap$pm" => "Stokes Library",
  "recap$pn" => "Lewis Library",
  "recap$pq" => "Harold P. Furth Plasma Physics Library",
  "recap$ps" => "Lewis Library",
  "recap$pt" => "Engineering Library",
  "recap$pw" => "Architecture Library",
  "recap$pz" => "Marquand Library",
  "recap$qk" => "Mendel Music Library",
  "recap$ql" => "East Asian Library",
  "recap$qv" => "Video Library",
  "recap$xc" => "Rare Books and Special Collections",
  "recap$xg" => "Rare Books and Special Collections",
  "recap$xm" => "Rare Books and Special Collections",
  "recap$xn" => "Rare Books and Special Collections",
  "recap$xp" => "Rare Books and Special Collections",
  "recap$xr" => "Rare Books and Special Collections",
  "recap$xx" => "Rare Books and Special Collections",
  "rare$warf" => "Rare Books and Special Collections" }

### PR DESCRIPTION
**Pull request by christinach**
closes #1168 

check back in the holding_library.rb file. It doesn't change.

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
Can we also in this PR remove the line from the indexing documentation that says it needs to be copied? https://github.com/pulibrary/bibdata/blame/alma/docs/indexing.md#L57

**Comment by christinach** [comment]
> Can we also in this PR remove the line from the indexing documentation that says it needs to be copied? https://github.com/pulibrary/bibdata/blame/alma/docs/indexing.md#L57

oh yes I will remove it.

**Comment by christinach** [comment]
@hackartisan can you check I removed the doc line and also an old comment for the specific issue.

**Review by hackartisan — APPROVED** [review]
👍🏻

**Pull request merged**
