### PR TITLE
Unavailable aeon items

### LINKED ISSUE #1989: Items in AEON with process_type: missing should have status label 'Unavailable'
### Desired behavior
Items in AEON with`process_type: missing` should have status label: 'Unavailable' in the availability response. https://github.com/pulibrary/bibdata/blob/040d5ac3f6157416bd1ca2b7bc54190394d735be/app/adapters/alma_adapter/status.rb#L26

### Current behavior
Items in AEON have status_label: 'On-site Access'. https://github.com/pulibrary/bibdata/blob/040d5ac3f6157416bd1ca2b7bc54190394d735be/app/adapters/alma_adapter/status.rb#L17
example: https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=9963575053506421
```

  "9963575053506421": {
    "22726823980006421": {
      "on_reserve": "N",
      "location": "rare$hsvm",
      "label": "Special Collections - Manuscripts",
      "status_label": "On-site Access",
      "copy_number": null,
      "cdl": false,
      "temp_location": false,
      "id": "22726823980006421"
    }
  }
}
```

Related issue https://github.com/pulibrary/orangelight/issues/3173

https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D%2Fholdings%2F%7Bholding_id%7D%2Fitems

### PR DESCRIPTION
**Pull request by maxkadel**
Closes #1989

### CODE REVIEW

**Comment by maxkadel** [comment]
Deployed to QA using Capistrano (pulbot was not working)

**Review by kevinreiss — APPROVED** [review]

**Comment by kevinreiss** [comment]
This PR looks good, but before deploying and merging we should discuss what the implications of this change is for the items that are in the "On Order" and "In Process" status since the status of these will also flip to unavailable and SC staff should be prepared for this change.

**Review by christinach — APPROVED** [review]

**Comment by kevinreiss** [comment]
Need to ping SC again.

**Comment by maxkadel** [comment]
Closing stale PR - see replacement, https://github.com/pulibrary/bibdata/pull/2056

**Pull request closed without merging**
